---
ID: "3afcd7f1-75d6-4d63-99a2-4a5a006251e3"
Parent: "953209bb-360f-431c-b2c5-4fbc3f7a7e95"
Template: "953209bb-360f-431c-b2c5-4fbc3f7a7e95"
Path: /sitecore/templates/TAC/Events/Content Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{A3746154-D2BE-4D9F-95DE-2C5D75FAF48A}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{02C030BB-4934-4B21-B4B2-91E464C942C3}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170612T153023Z
